#!/usr/local/bin/bash

show_help() {
  echo "proxmox-cli [METHOD] [PATH]

  FLAGS:
    -d | --data             add data to the api request.
    --debug                 print curl request without displaying auth token & cookie.
    --DEBUG                 print curl request with auth token & cookie.
    -h | --help             print helper.
    -H | --header           add custom http header to the request, e.g. \\\"--header \"YOUR_SUPER_HEADER: <your_value>\"\\\".

  COMMANDS:
    get                   request with \"GET\" method.
    post | create         request with \"POST\" method.
    put  | update         request with \"PUT\" method.
    del  | delete         request with \"DELETE\" method.
    token                 returns auth token.
    csrf                  returns CSRF Prevention Token.
    setup                 shows instruction to perform setup.

  USAGE:
    proxmox-cli get nodes mynode"
}

show_setup() {
  echo "Instructions to setup proxmox-cli, please run the following code snippet:
---
    read -p \"Please enter the base URL to one of your proxmox node (e.g. mynode.mahdhaoui.com): \" PM_URL
    read -p \"Please enter the port for proxmox: (e.g. 8006): \" PM_PORT
    read -p \"Please enter your user name: \" PM_USER_NAME
    read -p \"Please select your user domain (e.g. pam): \" PM_USER_DOMAIN
    read -sp \"Please enter your password: \" PM_PASS
    export PM_AUTH_COOKIE=\$(proxmox-cli token)
    export PM_CSRF_HEADER=\$(proxmox-cli csrf)
---"
}

PM_API_URL=https://${PM_URL}:${PM_PORT}/api2/json

auth() {
  curl -k -sL \
    -d "username=$PM_USER_NAME@$PM_USER_DOMAIN"\
    --data-urlencode "password=$PM_PASS" "$PM_API_URL/access/ticket"
}

# shellcheck disable=SC2016
AUTH_COOKIE="PVEAuthCookie=$PM_AUTH_COOKIE"
CSRF_HEADER="CSRFPreventionToken: $PM_CSRF_HEADER"
METHOD="GET"
HEADERS=""
REST_ENDPOINT=""
DEBUG=""
DATA=""

while [[ $# -gt 0 ]]; do
  case $1 in
    -h|--help)
      show_help
      exit 0;;
    -H|--header)
      HEADERS="$HEADERS --header \"$2\""
      shift;shift;;
    --header=*)
      HEADERS="$HEADERS --header ${1#*=}"
      shift;;
    -d|--data)
      DATA="$DATA -d $2"
      shift;shift;;
    --data=*)
      DATA="$DATA -d ${1#*=}"
      shift;;
    --debug)
      DEBUG=1
      shift;;
    --DEBUG)
      DEBUG=2
      shift;;
    -*|--*)
      echo "Unknown option $1"
      show_help
      exit 1;;
    get)
      METHOD=GET
      shift;;
    post|create)
      METHOD=POST
      shift;;
    put|update)
      METHOD=PUT
      shift;;
    del|delete|DEL|DELETE)
      METHOD=DELETE
      shift;;
    help)
      show_help
      shift;;
    token)
      auth | jq '.data.ticket' | sed 's/\"//g'
      exit 0;;
    csrf)
      auth | jq '.data.CSRFPreventionToken' | sed 's/\"//g'
      exit 0;;
    setup)
      show_setup
      exit 0;;
    *)
      REST_ENDPOINT="$REST_ENDPOINT/$1"
      shift;;
  esac
done

if [[ $REST_ENDPOINT == "" ]]; then
  echo -e "[ERROR] Please specify an endpoint as positional argument. E.g. proxmox get nodes 123"
  show_help
  exit 1
fi

URL="${PM_API_URL}${REST_ENDPOINT}"

cmd="curl -sL -k -X${METHOD} ${HEADERS} ${DATA} --url \"${URL}\""
if [[ $DEBUG == "1" ]]; then echo "$cmd"; fi

cmd="$cmd -b \"$AUTH_COOKIE\" --header \"${CSRF_HEADER}\""
if [[ $DEBUG == "2" ]]; then echo "$cmd"; fi

eval "$cmd"